const mongoose=require("mongoose");
const addressSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user",
        required:true, 
    },
    fullName:{
        type:String,
        required:true,
        trim:true,
        minlength:4,
        maxlength:50
    },
    phoneNo:{
        type:String,
        required:true,
        trim:true,
        minlength:10,
        maxlength:15,
    },
    addressLine:{
        type:String,
        required:true,
        trim:true,
        minlength:5,
        maxlength:150
    },
    city:{
         type:String,
        required:true,
        trim:true,
        minlength:2,
        maxlength:50
    },
    state:{
          type:String,
        required:true,
        trim:true,
        minlength:2,
        maxlength:50
    },
    pincode:{
          type:String,
        required:true,
        trim:true,
        minlength:6,
        maxlength:6
    },
     landmark:{
          type:String,
        required:true,
        trim:true,
        maxlength:100
    },
    addressType:{
        type:String,
        enum:["home","work","other"],
        required:true,
        default:"home"
    },
    isDefault:{
        type:Boolean,
        default:false,
    },
});
 const address=mongoose.model("address",addressSchema);
 module.exports=address;

 