const mongoose=require("mongoose");
const foodschema=mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
        minlength:10,
        maxlength:30
    },
    shortdescription:{
        type:String,
        trim:true,
        maxlength:200
    },
    description:{
        type:String,
        required:true,
        trim:true,
        minlength:20,
        maxlength:300,
    },
    cuisine:{
        type:String,
        required:true,
        enum:[
            "kolhapuri",
            "malvani",
            "khandeshi",
            "varhadi",
            "marathwada",
            "agrikoli",
            "pune",
            "solapuri"
        ],
        index:true
    },
    region:{
        type:String,
        required:true,
        trim:true,
        index:true
    },
    foodtype:{
        type:String,
        required:true,
       enum:["veg","non-veg"],
        index:true,
    },
    category:{
        type:String,
        requried:true,
        trim:true,
        index:true,
    },
    price:{
        type:Number,
        required:true,
        min:1
    },
    images:[
        {
            url:{
                type:String,
                required:true,
            },
            alttext:{
                type:String,
                default:""
            }
        }
    ],
    ingredients:[
        {
            type:String,
            trim:true,
        }
    ],
    spicelevel:{
        type:String,
        enum:[
            "mild",
            "medium",
            "spicy",
            "very-spicy"
        ],
        default:"medium",
    },
    servingsize:{
        type:String,
        required:true,
        trim:true,
    },
    preprationtime:{
        type:Number,
        default:true,
        index:true,
    },
    isavailabel:{
        type:Boolean,
        default:true,
        index:true,
    },
    isactive:{
        type:Boolean,
        default:true,
        index:true,
    },
    cook:{
   type:mongoose.Schema.Types.ObjectId,
   ref:"User",
   required:true,
   index:true
    }
},
{
    timestamps:true
}
);
module.exports=mongoose.model("food",foodschema);