const mongoose=require("mongoose");
const foodschema=mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true,
        minlength:10,
        maxlength:30
    },
    shortDescription:{
        type:String,
        trim:true,
        maxlength:200
    },
    description:{
        type:String,
        required:true,
        trim:true,
        minlength:20,
        maxlength:300,
    },
    cuisine:{
        type:String,
        required:true,
        enum:[
            "kolhapuri",
            "malvani",
            "khandeshi",
            "varhadi",
            "marathwada",
            "agrikoli",
            "pune",
            "solapuri"
        ],
        index:true
    },
    region:{
        type:String,
        required:true,
        trim:true,
        index:true
    },
    foodType:{
        type:String,
        required:true,
       enum:["veg","non-veg"],
        index:true,
    },
    category:{
        type:String,
        required:true,
        trim:true,
        index:true,
    },
    price:{
        type:Number,
        required:true,
        min:1
    },
    images:[
        {
            url:{
                type:String,
                required:true,
            },
            altText:{
                type:String,
                default:""
            }
        }
    ],
    ingredients:[
        {
            type:String,
            trim:true,
        }
    ],
    spiceLevel:{
        type:String,
        enum:[
            "mild",
            "medium",
            "spicy",
            "very-spicy"
        ],
        default:"medium",
    },
    servingSize:{
        type:String,
        required:true,
        trim:true,
    },
    preparationTime:{
        type:Number,
        required:true,
        min:1,
        index:true,
    },
    isAvailable:{
        type:Boolean,
        default:true,
        index:true,
    },
    isActive:{
        type:Boolean,
        default:true,
        index:true,
    },
    cook:{
   type:mongoose.Schema.Types.ObjectId,
   ref:"User", 
   required:true,
   index:true
    }
},
{
    timestamps:true
}
);
module.exports=mongoose.model("Food",foodschema);